ERROR CAUSED BY NEW VERSION OF PYSTRAY WHEN RUNNING WITH PYINSTALLER!

At the testing time (May 2020), when running the exe file generated by PyInstaller, package 'pystray' version 1.6 produced following error:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
  File "d:\code\git\personal\popuptranslator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "tray.py", line 2, in <module>
  File "d:\code\git\personal\popuptranslator\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\pystray\__init__.py", line 48, in <module>
  File "lib\site-packages\pystray\__init__.py", line 45, in backend
ImportError: this platform is not supported: No module named 'pystray._win32'

This error only happens in the exe file generated by PyInstaller. Not when running the scripts.

There are solutions to fix this kind of error (such as https://stackoverflow.com/a/46205767) though we have not tried any of them.
But they're all about fixing the source code of pystray. This is out of our scope.

So, our temporary (yet quick) solution is to use the old 'pystray' version 1.5 instead of the new ones.
This version (pystray and pystray-0.15.0.dist-info) can be found in "PopupTranslator/backup/Lib/site-packages"
You just need to replace (delete then copy) the new pystray by the 1.5-version one.
