[2020-09-13 17:17:34] [ERROR] [translator.py] [translate() - 22]: Failed to translate! Details: HTTPConnectionPool(host='api.mymemory.translated.net', port=80): Max retries exceeded with url: /get?q=against&langpair=ja%7Cen (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000157A0B02B38>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
